apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: targeting-service-secret
  namespace: targeting-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: targeting-service-secret
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: targeting-service-dev/database-url
