apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  namespace: targeting-service
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9maWFwOmJoaW1BMTIzQHRvZ2dsZS1tYXN0ZXItZGIuY2hyMWRnc283YnlnLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL3RvZ2dsZW1hc3Rlcj9zc2xtb2RlPXJlcXVpcmU=
